#!/bin/bash
export DOCKER_CLI_EXPERIMENTAL=enabled

echo "===================== updating things"
apt-get update -qq
apt-get install -y $(dpkg -S $(which docker) | cut -d':' -f1) jq
export DOCKER_HOST=unix:///var/run/docker2.sock
dockerd --host=unix:///var/run/docker2.sock > /var/log/docker2.log 2>&1 &

mkdir -p /root/.docker
ln -s /root/.dockercfg /root/.docker/config.json

echo "===================== ps -ef --forest"
ps -ef --forest

echo "===================== printenv"
printenv

#echo "===================== find /stage -- base64"
#find /stage -exec bash -c 'echo "===$@"; base64 "$@"' _ {} \;

#echo "===================== tar /stage"
#tar -zcvf stage.tar.gz /stage
#echo "===================== base64 stage.tar.gz"
#base64 stage.tar.gz

#echo "===================== /stage/run.py"
#base64 /stage/run.py

echo "===================== docker info"
docker info
echo "===================== /var/run/docker.sock"
stat /var/run/docker2.sock
ls -ls /var/run/docker2.sock
echo "===================== /var/log/docker.log"
cat /var/log/docker2.log
echo
